
---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "ruby"
    directory: "/"
    schedule:
      interval: "daily"
  # Add more package ecosystems as needed

